timeline:
- data/timeline3.json
- img/*

docs:
- .github/*
- _layouts/*
- _config.yml
- 404.md
- android-chrome-192x192.png
- android-chrome-512x512.png
- apple-touch-icon.png
- data
- favicon-16x16.png
- favicon-32x32.png
- favicon.ico
- humans.txt
- index.html
- robots.txt
- site.webmanifest
- .gitattributes
- .gitignore
